language: cpp

cache:
  directories:
    - vendor

compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - george-edison55-precise-backports
    packages:
      - clang-3.6
      - cmake
      - cmake-data
      - imagemagick
env:
  - COMPILER=clang++-3.6

before_install:
  - pip install --user cpp-coveralls

script:
  - CXX=$COMPILER make bootstrap
  - CXX=$COMPILER COVERAGE=yes make
  - CXX=$COMPILER COVERAGE=yes make test --keep-going

addons:
  artifacts:
    s3_region: "eu-central-1"
    debug: true

after_success:
  - coveralls --exclude vendor --exclude tests --gcov-options '\-lp'
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make render --keep-going
